### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-ui-ux#106]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
Hi @bhanuja-s @rainbj  , a friendly reminder to help review by next week as we want every SIG to have a roadmap according to the RFC attached above by February 6th, 2023.

**Comment by bhanuja-s** [comment]
Hey @vincent6767, @rainbj and I were talking about this issue and @yuyihsu created sig-ui-ux's roadmap for us a long time ago here: https://github.com/orgs/o3de/projects/9/views/1. Is this what you're looking for or is there something specific we're missing. Thank you!

**Comment by rainbj** [comment]
We are also working on creating a more condensed view of upcoming projects (future state). However, we cannot commit to anything on that list until we get feedback from the development team if these are issues are going to be picked up in 2023.

**Comment by vincent6767** [comment]
Hi @bhanuja-s @rainbj 
Yes, that's what I mean by the roadmap view! But it does not yet meet the RFC requirements. See these sections in the RFC: https://github.com/o3de/sig-release/issues/79
1. Processes - Roadmap item
2. Processes - SIG Roadmap View setup.
3. Processes - Add a new template "Add a roadmap Item"

Based on above mentioned sections, what is missing is which items are considered roadmap items. The roadmap item is labeled with a kind/roadmap.

**Comment by rainbj** [comment]
@vincent6767 we are having a bit of confusion here. We work on researching and creating tickets for issues for RTE (rev the engine) program for things we find (issues with the engine), but ultimately we are not working on these tickets.  So the question because these tickets get added to other team roadmap how you like to proceed? Should we be adding the label kind/roadmap to only tickets we work on personally (as a team) or tickets that will be things the team will work on this upcoming year?

**Comment by vincent6767** [comment]
Hi @rainbj 
> Should we be adding the label kind/roadmap to only tickets we work on personally (as a team) or tickets that will be things the team will work on this upcoming year?

You only need to manage tickets you and the SIG UI/UX work personally as a team. Other teams who work on your tickets will list those as part of their roadmap if they see it's necessary. Hope it clears up your confusion.

**Comment by vincent6767** [comment]
Hi! I see you have created the roadmap and also labeled the issue with the kind/roadmap. Thanks! I'll close this issue @rainbj @bhanuja-s 

I also move forward linking the roadmap into this repo. You can see it in here: https://github.com/o3de/sig-ui-ux/projects?query=is%3Aopen
