### ISSUE TITLE
Proposed SIG-UI-UX meeting agenda for MMMM-DD-YY

### ISSUE THREAD

**Issue by rainbj** [o3de/sig-ui-ux#19]
## Meeting Details

- **Date/Time:** 07 22, 2021 @ XX:XXpm UTC / XX:XXpm ET
- **Location:** [Discord SIG-UI-UX Voice Room](https://discord.gg/Mc6jStmuMK)
- **Moderator:** TBA
- **Note Taker** Person

The [SIG-UI-UX Meetings](https://github.com/o3de/sig-ui-ux/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

**What happened since the last meeting?**

## Meeting Agenda

**Discuss agenda from proposed topics**

## Outcomes from Discussion topics

**Discuss outcomes from agenda**

## Action Items

**Create actionable items from proposed topics**

## Open Discussion Items

List any additional items below!

**Comment by AMZN-Liv** [comment]
@rainbj - can you update the date/time for this? Someone asked about it in Discord

**Comment by rainbj** [comment]
This agenda item was open as a duplicate. Closing.
