### ISSUE TITLE
SIG UX-UI bi-weekly update - RTE, BlueJay, matieral editor workflow feedback

### ISSUE THREAD

**Issue by rainbj** [o3de/sig-ui-ux#50]
## UI-UX SIG Meeting — today's content for 01-19-2022

Hi O3DE Community,
We want to invite you to our meeting program feedback, RTE updates, triage, and design specific conversations.  The purpose is to discuss the UX gap with the community and the team. Talk about the plan and what needs to change and create a  direction for us  to help best resolve these issues. 

## Schedule:
- **Date/Time:** 01-19-2022 @ 10:00am PT
- **Location:** [Discord SIG-UI-UX Voice Room](https://discord.gg/Mc6jStmuMK)
- **Moderator:** UI/UX SIG Committee
- **Note Taker** UI/UX SIG Committee

## Meeting Details:
We want to invite you to our Sig UX UI  bi-weekly meeting*.* This is a bi-weekly meeting and we will cover the following items from the UX team.

## Agenda items:
1. UI-UX SIG meeting format update
2. Update on the Rev the Engine Program. 
3. Update on the BlueJay Design System roadmap.
4. Customer insight learning @Finchy [Amazon, Finch Studio] will share their feedback on the material editing workflow.

Let us know if there's other topic you'd like to talk about in our meeting tomorrow by adding a comment to this ticket

## Other items covered in this meeting.
• Ticket triage - We will go through our ticket backlog and do prioritization and sorting
• Review outstanding ticket assigned previously.
•RTE program updates and new details. Any new findings, results, or feedback.
• Check in with designer about problems they are facing regarding tickets and if any help is required
• Feedback from any research previously done regarding tickets.
• Assign designers or UI-UX SIG members UX work. This includes deadlines and expectations of work completed. 
• In some cases a show and tell may be required to talk through a pending issue or new feature. However we we’ll try to hold these for design critiques for every other Wednesday.
• Request for research and or conduct live research.
• Close out tickets if completed.

The [SIG-UI-UX Meetings](https://github.com/o3de/sig-ui-ux/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## To sign up for a topic in the SIG-UI-UX Bi-weekly meeting. 
- Please add a **comment** to this ticket with following information:
 - **Discord name:**
 - **Topic of conversation:**
 - **How much time you might need:**
 - **Any UX resource you have already been working with and if their attendance is required.**
 - ** Any resource to help explain your issue **

## How can I use the Bi-weekly meeting?
• Please add any specific agenda items you would like to talk about to the [ticket](https://github.com/o3de/sig-ui-ux/issues). 
• We will address any agenda items first. These items should be related to outstanding tickets. 
• This meeting is not about creating new tickets but reviewing and fixing outstanding tickets.
• If you have speciality such as research, design, or a unique understanding of game development. Let us know so we can help facilitate where we can use your help the most.
• Offer to be a note taker. We always need some help here. Facilitating a meeting and being a note taker can be tough, so any one willing to help will be appreciated. 
• Offer to be a person willing to help put together agenda items and or review agenda items from previous meetings.

## What should I bring to the bi-weekly meeting?
• Nothing is required but the following items would be helpful
o A list of ticket you are interested in addressing
o An update on tickets you have been working on
o Some prepared questions about the tickets you own 

## Cut-off time / cancellation 
• For the UI/UX bi-weekly meeting the UI-UX SIG team will check the GitHub Agenda item ticket 24 hours before the scheduled meeting, if no one signs up in the session, we will lock down the agenda of that day.
• If you are unable to attend after signing up, Please just reach out in discord or on the ticket to let us know about the change.

**Comment by amzn-leenguy** [comment]
Customer insight learning - @Finchy [Amazon, Finch Studio] will share her feedback on the material editing workflow. (30 mins)

**Comment by finchy** [comment]
@finchy is me.  Not Amazon.

**Comment by amzn-leenguy** [comment]
> @finchy is me. Not Amazon.

My mistake. I have removed your tag from the comment now.

**Comment by finchy** [comment]
Not a problem!

**Comment by aFinchy** [comment]
I had to go with aFinchy on github

**Comment by finchy** [comment]
Sorry!  I beat you to it.
