### ISSUE TITLE
10/25/2022 - SIG UX-UI - today's newest content - <THIS WEEKS TOPIC>

### ISSUE THREAD

**Issue by rainbj** [o3de/sig-ui-ux#85]
## Monthly SIG UI-UX  Business review for 10-25-2022

Hi O3DE UX Community,  
 
We want to invite you to our monthly UI-UX business review. In each of our monthly meetings, we will send out a reminder a week ahead of time, allowing UI-UX community members to propose a topic that matter the most to them. These chats might include, new designs, new patterns, research, new workflows, chats with a specialist, or even a water cooler conversation. Come join us around the virtual table and let's talk shop. Feel free to add your topic to the ticket https://github.com/o3de/sig-ui-ux/issues, and we will do our best to plan accordingly. 
 
A small side note. This meeting will be different from our open office hour meeting that is scheduled every Thursday. This monthly meeting will be used to talk about the larger picture, and what's our goal to get there. We won't be focusing on individual bugs or release issues.

 ## This weeks conversation:    
Please see this month's ticket for topics https://github.com/o3de/sig-ui-ux/issues. We will cover topics on first come, first served, method. However, we will try to accommodate as many people as we can in an hour 
 
 ## Schedule
- **Date/Time:** 10/25/2022 @ 11:00am Pacific Time (PT) 
- **Location:** [Discord SIG-UI-UX Voice Room](https://discord.gg/Mc6jStmuMK)
- **Moderator:** SIG-UI-UX Committee
- **Note Taker** SIG-UI-UX Committee

## Past meetings:
 https://github.com/o3de/sig-ui-ux/issues?q=is%3Aissue+is%3Aclosed+todays+in%3Atitle

## To sign up for a topic:
 - Please add a **comment** to this ticket with following information
   - Discord name.
   - Topic of conversation.  
   - How much time you might need.  
   - Any UX resource you have already been working with and if their attendance is required.  
   - Any resources you might need. 

 
## How can I participate in the UI UX community outside just this meeting? 
• Great question! If you have a specialty such as research, design, or a unique understanding of game development. Let us know, so we can help facilitate conversation on how best to contribute.  
• Offer to be a note taker. We always need some help here. Facilitating a meeting and being a note taker can be tough, so anyone willing to help will be appreciated. 
• Offer to be a person willing to help put together agenda items and or review agenda items from previous meetings.
• Talk with one of the committee members about working on UX related tickets.
 
## What should I bring to the meeting?
• Nothing, unless you're the presenter. Just your attendance, and your conversation on the topic.

## Cut-off time or cancellation 
• The UI-UX SIG team will check the ticket 24 hours before the scheduled meeting. At that point we will lock down the agenda of that day. 
• If you are unable to attend after signing up, please just reach out in discord or on the ticket to let us know before the meeting starts.

**Comment by bhanuja-s** [comment]
This meeting was cancelled!
