### ISSUE TITLE
10-20-2022 – SIG-UI-UX Office Hours (Add your request in comments)

### ISSUE THREAD

**Issue by bhanuja-s** [o3de/sig-ui-ux#91]
## SIG-UI-UX Office Hours for 10-20-2022

Hi O3DE Community,
We want to invite you to our UX design review and office hours. 

- **Date/Time:**  10/20/2022 @ 9:00am PT
- **Location:** [Discord SIG-UI-UX Voice Room](https://discord.gg/Mc6jStmuMK)
- **Moderator:** UI/UX SIG Committee
- **Note Taker** UI/UX SIG Committee

The [SIG-UI-UX Meetings](https://github.com/o3de/sig-ui-ux/tree/main/meetings) repo contains the history of past calls, including a link to the agenda, recording, notes, and resources.

## To sign up the Office Hours. <br>Please add a **comment** to this ticket with the following information:
- **Discord username:**
- **Topic of conversation:**
- **How much time you might need:**
- **Any UX resource you have already been working with and if their attendance is required.**

##  This is a weekly meeting will cover the following items.
- SIG UI-UX team will show some O3DE workflows that are currently in-progress.
- SIG UI-UX will provide feedback to others about their O3DE feature design work.
- SIG UI-UX have open conversations about UX/UI related problems coming down the pipeline.
- Triage SIG UI-UX related tickets

## How do I sign up to get feedback?
- You can sign up by going to https://github.com/o3de/sig-ui-ux/issues 
- Find the specific event you are interested in attending and getting feedback on.
   - In the comment section of that ticket, place the details you would like to talk about. 
   - Please include your name and/or Discord Name
   - The area of topic you would like to cover
   - The amount of time you might need to review this topic
   - Any individuals you have been already working
   - Any specific people you would like to attend this session for help.

## How can I use office hours:
- Request a “sign-off” on your project from the UI-UX SIG.
- Usability/UX review of your designs/mock-ups.
- Discuss certain customer pain points or UX related topics.
- Brainstorm ideas or solutions to a user problem or feature.
- Submit user research or UX design requests.
What should I bring to the office hour:
- Nothing is required, but the following items would be helpful 
   - A brief project overview or documentation, This should include the following 
   - A simple user problem statement. As a user, I want to solve this problem…
   - Who is your audience? Who are the users/user groups affected by the change?
   - What is your vision behind this change or update?
   - What is your UX issue related to: user interface, usability testing, learnability, documentation etc?
   - Materials/Workflows of the existing product. Sketches or wire-frames of ideas. PR/FAQ are also help.

**Comment by greerdv** [comment]
I think physics was recently noted in user studies as one of the areas most in need of improvement, so I'd like to do a review of what concrete things can be improved. Below are some of the areas we are already aware of having problems
- settings are hard to find and distributed between many locations e.g. asset editor, physx configuration window, fbx settings, component cards etc
- users are not discovering all the options in the fbx settings e.g. convex decomposition, primitive fitting
- no preview or feedback in fbx settings, have to switch between there and editor to see updates to exported collision geometry
- it is not clear to users that a physx collider component without a rigid body component will create a static body
- problems with teleporting, moving static bodies etc
- PhysX debug is a separate gem which is not enabled by default, which causes problems with debug draw and connecting to the PhysX visual debugger
Some of these we have already discussed with sig-ui-ux and have pretty solid ideas how to make improvements, it just comes down to fitting the work into other schedule commitments. But I'd like to figure out if there is anything not on this list which we should be thinking about, and also try to figure out what would be the highest priority items to address.
